### ISSUE TITLE
Auth page minor frontend details

### ISSUE THREAD

**Issue by arnaugamez** [UB-ES-19/F2-Quora#13]
Hi there, there are some frontend details to be refined:

1) Register and Login titles appear way bigger than original
2) Register and Login buttons appear quite weird, they should have CSS style matching the original.
3) The “square” containing the register and login forms is not exactly in the very center. Check with original page. Also background picture seems to load at different height, so it appears like moved upwards.
4) Finally, the interface is in Spanish. I don’t know if we want to keep it, move to only english or try to make some i18n effort. We can ask to Product Owner.

CC @lousmontabes @jperacaula @marinavc

**Comment by jperacaula** [comment]
Hi, 

1. Register and Login titles appear way bigger than original -> Solved

And I add another detail to solve:
5. Add log in fields placeholders.

I've tried it in several ways, but I couldn't.

**Comment by marinavc** [comment]
Hi,

1. solved
2. maybe it's not necessary
3. Image looks right, center is maybe not that relevant
4. Did we ask PO about this?
5. I don't know how relevant this is since we found out we don't have to identically copy Quora but i have found a link explaining how to add placeholders in Django forms (https://stackoverflow.com/questions/4101258/how-do-i-add-a-placeholder-on-a-charfield-in-django) it looks like it should be done inside the Form declaration using 'widget' so I'm not sure if this is a frontend or backend issue, that's why I haven't tried it yet.

@jperacaula @arnaugamez @lousmontabes @LukazMartin

**Comment by arnaugamez** [comment]
Hi, I think the only relevant stuff now here is the one about i18n, as we don’t need to make an exact copy. We can ask PO on next week’s sprint review. I am closing this issue; when we know about i18n we could open a specific one.
