### ISSUE TITLE
US9- Follow other Users

### ISSUE THREAD

**Issue by LukazMartin** [UB-ES-19/F2-Quora#67]
I did the backend part of this US. For adding a user in your following list you have to call follow(request,UserToFollow) in the views.py. Are we implementing also an action for unfollow people? because it was not included in the User Stories

**Comment by jperacaula** [comment]
I think so. Or at least yesterday with Marina we decided to add a button to unfollow in case of following.

**Comment by marinavc** [comment]
Yes we discussed a button changing from follow/unfollow depending on current state. In the profile template I will just implement the button display and change, I leave all checks (if user is me or other, if user is followed already or not) for @lousmontabes since it implies passing info as context and I don't know which info will be available
